on:
  push:
    branches:
      - main
      - 'releases/**'

jobs:
  docs:
    needs: coco

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: generate html files for sphinx
        run: |
          ./make.bat html
